name: flutter CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
      - name: Get Packages
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter build
        run: flutter build appbundle --release
